<a href="https://colab.research.google.com/github/nishan2001/ML-From-Scratch/blob/main/01_Introduction_to_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

What will we cover?
- Creating arrays
- Multi dimensional array
- Randomly generated arrays
- Element wise operations
     - Comparisond operation
     - Logical operations
- Summarizing operations


### Single dimension array


In [1]:
import numpy as np

Creating arrays

In [3]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
var = np.array([1, 2, 3, 4])
var[3]=5
print(var)

[1 2 3 5]


In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

### Create arrays with evenly spaced numbers within a specified range

```
# This is formatted as code
```



In [13]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multi Dimension array

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# create an MD unit array of size (5,
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
#Generate a random array of size (3,5) with elements of your choice
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
#Generate a random array of size (3,5) with elements of random int
np.array(np.random.randint(5, size=(3, 5)))

array([[4, 4, 0, 0, 4],
       [0, 1, 2, 2, 1],
       [0, 3, 0, 0, 2]])

In [33]:
#update the elemnt of an array with index
n= np.array  ([[1, 2, 3, 4, 5],
      [2, 3, 4, 5, 6],
    [4, 5, 6, 7, 8]])
n

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [34]:
n[: , 2] = 2
n


array([[1, 2, 2, 4, 5],
       [2, 3, 2, 5, 6],
       [4, 5, 2, 7, 8]])

### Randomly generated arrays

-NumPy can create arrays filled with random numbers.
-To ennsure the reproducibility, you can set a seed using np.random.seed()

-Everytime you run the code with np.random.seed(2),it will generate the exact same random nombers .

if you remove or change the seed values, the sequence of random nmbers will be changed

In [35]:
np.random.rand(3)

array([0.01872471, 0.16149408, 0.7111481 ])

In [46]:
np.random.seed(3)
np.random.rand(3)

array([0.5507979 , 0.70814782, 0.29090474])

In [48]:
np.random.rand(5, 2)

array([[0.27848728, 0.6762549 ],
       [0.59086282, 0.02398188],
       [0.55885409, 0.25925245],
       [0.4151012 , 0.28352508],
       [0.69313792, 0.44045372]])

In [53]:
#rand ranges from 0 to 1
np.random.seed(3)
np.random.rand(5, 2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

In [61]:
#randomly normally distriuted
np.random.randn(5, 2)

array([[-1.3957635 ,  1.39166291],
       [-1.37066901,  0.23856319],
       [ 0.61407709, -0.83791227],
       [ 0.14506321,  1.16788229],
       [-0.02410447, -0.88865742]])

In [62]:
np.random.seed(3)
np.random.randint(low=0, high=100, size=(5, 2))

array([[24,  3],
       [56, 72],
       [ 0, 21],
       [19, 74],
       [41, 10]])

### Element wise Operations

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [67]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [69]:
#Comparison operations
# You can perform element -wise comparisons and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [71]:
a >= 2

array([False, False,  True,  True,  True])

In [72]:
a > b

array([False, False, False, False, False])

In [73]:
# Summarizing
#NumPy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [74]:
#Standar deviation
a.std()

1.4142135623730951

In [75]:
#min vale of array
a.min()

0

In [76]:
#max value of array
a.max()

4

In [77]:
#sum of the elementss of array
a.sum()

10

In [78]:
#mean of the array
a.mean()

2.0